export const browserCoreExamples = [
  "forge-orchestrator browser status",
  "forge-orchestrator browser start",
  "forge-orchestrator browser stop",
  "forge-orchestrator browser tabs",
  "forge-orchestrator browser open https://example.com",
  "forge-orchestrator browser focus abcd1234",
  "forge-orchestrator browser close abcd1234",
  "forge-orchestrator browser screenshot",
  "forge-orchestrator browser screenshot --full-page",
  "forge-orchestrator browser screenshot --ref 12",
  "forge-orchestrator browser snapshot",
  "forge-orchestrator browser snapshot --format aria --limit 200",
  "forge-orchestrator browser snapshot --efficient",
  "forge-orchestrator browser snapshot --labels",
];

export const browserActionExamples = [
  "forge-orchestrator browser navigate https://example.com",
  "forge-orchestrator browser resize 1280 720",
  "forge-orchestrator browser click 12 --double",
  'forge-orchestrator browser type 23 "hello" --submit',
  "forge-orchestrator browser press Enter",
  "forge-orchestrator browser hover 44",
  "forge-orchestrator browser drag 10 11",
  "forge-orchestrator browser select 9 OptionA OptionB",
  "forge-orchestrator browser upload /tmp/file.pdf",
  'forge-orchestrator browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "forge-orchestrator browser dialog --accept",
  'forge-orchestrator browser wait --text "Done"',
  "forge-orchestrator browser evaluate --fn '(el) => el.textContent' --ref 7",
  "forge-orchestrator browser console --level error",
  "forge-orchestrator browser pdf",
];
