#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${FORGE_ORCH_INSTALL_E2E_IMAGE:-${FORGE_ORCH_INSTALL_E2E_IMAGE:-forge-orchestrator-install-e2e:local}}"
INSTALL_URL="${FORGE_ORCH_INSTALL_URL:-${FORGE_ORCH_INSTALL_URL:-https://forge-orchestrator.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
FORGE_ORCH_E2E_MODELS="${FORGE_ORCH_E2E_MODELS:-${FORGE_ORCH_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e FORGE_ORCH_INSTALL_URL="$INSTALL_URL" \
  -e FORGE_ORCH_INSTALL_TAG="${FORGE_ORCH_INSTALL_TAG:-${FORGE_ORCH_INSTALL_TAG:-latest}}" \
  -e FORGE_ORCH_E2E_MODELS="$FORGE_ORCH_E2E_MODELS" \
  -e FORGE_ORCH_INSTALL_E2E_PREVIOUS="${FORGE_ORCH_INSTALL_E2E_PREVIOUS:-${FORGE_ORCH_INSTALL_E2E_PREVIOUS:-}}" \
  -e FORGE_ORCH_INSTALL_E2E_SKIP_PREVIOUS="${FORGE_ORCH_INSTALL_E2E_SKIP_PREVIOUS:-${FORGE_ORCH_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
